[package]
name = "tokens"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html
[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.39.0" }

[dependencies]
openzeppelin = "0.20.0"

[[target.starknet-contract]]
casm = true

[scripts]
test = "snforge test"